config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'
  get 'dashboard/index'

  get 'dashboard/exam_1'
  post 'dashboard/get_prime'

  get 'dashboard/exam_2'
  post 'dashboard/get_user_game'

  get 'dashboard/exam_3'
  post 'dashboard/get_user_game_hard'

  get 'dashboard/exam_4'

  get 'dashboard/exam_5'

  get 'dashboard/exam_6'

  get 'dashboard/exam_7'

  get 'dashboard/exam_8'

  get 'dashboard/exam_9'

  get 'dashboard/exam_10'

  devise_for :users

end

app/models/creators_game.rb
class CreatorsGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :users_games
  has_many :users, through: :users_games
  has_many :creators_games
  has_many :creators, through: :creators_games, source: :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  before_validation :set_password

  has_many :users_games
  has_many :games, through: :users_games
  has_many :creators_games
  has_many :own_games, through: :creators_games, source: :game

  def set_password
    generated_password = Devise.friendly_token.first(8)
    self.password ||= generated_password
    self.password_confirmation ||= password
  end
end

app/models/users_game.rb
class UsersGame < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options={})
    { locale: I18n.locale }
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def exam_1
  end

  def get_prime
    ### exam_1 ####
    @result = nil
  end

  def exam_2
    @user_game = User.all.map { |u| { u.email => u.games.count } }.sort_by(&:values).last
  end

  def get_user_game
    ### exam_2                          ###
    ### u can send more global variable ###
    @result = User.new
  end

  def exam_3
  end

  def get_user_game_hard
    ### exam_3                            ###
    ### return user                       ###
    ### Can't add more global variable    ###
    ### Try to make everything in 1 query ###
    @result = User.new
  end

  def exam_4
    ### exam 4                                                            ###
    ### your have to set current_user as a user that have at least 1 game ###
    ### You can change global variable                                    ###
    #@current_user = nil ### have to change by random with at least 1 game ###
    @games = Game.all

    @current_user = User.find(UsersGame.pluck(:user_id).sample)
  end

  def exam_5
    ### exam 5                                                            ###
    ### your have to set current_user as a user that have at least 1 game ###
    ### You can change global variable                                    ###
    @current_user = nil ### have to change by random with at least 1 game ###
    @games = Game.all
  end

  def exam_6
    @games = Game.limit(5)

    @games_count_users = @games.map do |g|
      [
        g.name,
        UsersGame.where(game_id: g.id).count,
        User.find(UsersGame.where(game_id: g.id).pluck(:user_id)).map(&:email).join(', ')
      ]
    end
  end

  def exam_7
    all_game_ids = Game.pluck(:id)
    all_game_ids_someone = UsersGame.pluck(:game_id).uniq

    all_game_ids_noone = all_game_ids - all_game_ids_someone

    @all_games_noone = Game.find(all_game_ids_noone).map(&:name)
  end

  def exam_8
    @games = Game.limit(5)

    @games_count_users = @games.map do |g|
      [
        g.name,
        g.price,
        UsersGame.where(game_id: g.id).count,
        UsersGame.where(game_id: g.id).count * g.price,
      ]
    end
  end

  def exam_9
    @self_bought_games = []

    User.all.each do |u|
      bought_games = u.games
      own_games    = u.own_games

      @self_bought_games << (bought_games & own_games)
    end

    @self_bought_games.flatten!
  end

  def exam_10
    @games = Game.limit(5)

    @games_count_users = @games.map do |g|
      [
        g.name,
        UsersGame.where(game_id: g.id).count,
        User.find(UsersGame.where(game_id: g.id).pluck(:user_id)).map(&:email),
        g.creators.map(&:email)
      ]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def t_(key, options = {})
    I18n.t("general.#{key}", options)
  end

  def t_locale(key, options = {})
    I18n.t("locales.#{key}", options)
  end

  def t_title(key, options = {})
    I18n.t("titles.#{key}", options)
  end

  def t_exam(number)
    I18n.t("exam", number: number)
  end

  def t_exam_title(key, options = {})
    I18n.t("exames.#{key}.title", options)
  end

  def t_exam_content(key, options = {})
    I18n.t("exames.#{key}.content", options)
  end

  def t_boolean(boolean)
    raw '<i class="fa fa-check"></i>' if boolean
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/exam_1.html.erb
<h1><%= t_exam_title(:exam_1) %></h1>
<p><%= t_exam_content(:exam_1) %></p>


<%= form_tag dashboard_get_prime_path, remote: true do %>
  <%= text_field_tag :number %>
  <%= submit_tag t_(:get) %>
<% end %>

<h2 id="result-get-prime">
  <%= t_(:answer) %>
</h2>
<!--



 -->

app/views/dashboard/exam_10.html.erb
<div>
  <h1><%= t_exam_title(:exam_10) %></h1>
  <p><%= t_exam_content(:exam_10) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
        <th><%= t_(:count) %></th>
        <th><%= t_(:users) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <% @games_count_users.each do |g| %>
        <tr>
          <td><%= g[0] %></td>
          <td><%= g[1] %></td>
          <td>
            <% g[2].each do |email| %>
              <% if email.in? g[3] %>
                <strong style="color:red;"><%= email %></strong>
              <% else %>
                <%= email %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_2.html.erb
<h1><%= t_exam_title(:exam_2) %></h1>
<p><%= t_exam_content(:exam_2) %></p>


<%= form_tag dashboard_get_user_game_path, remote: true do %>
  <%= submit_tag t_(:get) %>
<% end %>

<h2 id="result-get-prime">
  <%= t_(:email) %>: <span class="user"><%= @user_game.keys.first -%></span>
  <%= t_(:count) %>: <span class="count"><%= @user_game.values.first -%></span>
</h2>
<!--



 -->

app/views/dashboard/exam_3.html.erb
<h1><%= t_exam_title(:exam_3) %></h1>
<p><%= t_exam_content(:exam_3) %></p>


<%= form_tag dashboard_get_user_game_hard_path, remote: true do %>
  <%= submit_tag t_(:get) %>
<% end %>

<h2 id="result-get-prime">
  <%= t_(:email) %>: <span class="user"></span>
  <%= t_(:count) %>: <span class="count"></span>
</h2>
<!--



 -->

app/views/dashboard/exam_4.html.erb
<div>
  <h1><%= t_exam_title(:exam_4) %></h1>
  <p><%= t_exam_content(:exam_4) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
        <th><%= t_(:have) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <%- current_user_game_ids = @current_user.games.pluck(:id) -%>

      <% @games.each do |game| %>
        <tr>
          <td><%= game.name %></td>
          <td><%= game.id.in?(current_user_game_ids) ? 'Yes' : '' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_5.html.erb
<div>
  <h1><%= t_exam_title(:exam_5) %></h1>
  <p><%= t_exam_content(:exam_5) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
        <th><%= t_(:have) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <% @games.each do |game| %>
        <tr>
          <td><%= game.name %></td>
          <td><%= t_boolean(false) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_6.html.erb
<div>
  <h1><%= t_exam_title(:exam_6) %></h1>
  <p><%= t_exam_content(:exam_6) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
        <th><%= t_(:count) %></th>
        <th><%= t_(:users) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <% @games_count_users.each do |gcu| %>
        <tr>
          <td><%= gcu[0] -%></td>
          <td><%= gcu[1] -%></td>
          <td><%= gcu[2] -%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_7.html.erb
<div>
  <h1><%= t_exam_title(:exam_7) %></h1>
  <p><%= t_exam_content(:exam_7) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <%- if @all_games_noone.blank? -%>
        <tr>
          <td>No games</td>
        <tr>
      <%- else -%>
        <% @all_games_noone.each do |g| %>
          <tr>
            <td><%= g %></td>
          </tr>
        <% end %>
      <%- end -%>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_8.html.erb
<div>
  <h1><%= t_exam_title(:exam_8) %></h1>
  <p><%= t_exam_content(:exam_8) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
        <th><%= t_(:price) %></th>
        <th><%= t_(:count) %></th>
        <th><%= t_(:sum) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <% @games_count_users.each do |gcu| %>
        <tr>
          <td><%= gcu[0] -%></td>
          <td><%= gcu[1] -%></td>
          <td><%= gcu[2] -%></td>
          <td><%= gcu[3] -%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/exam_9.html.erb
<div>
  <h1><%= t_exam_title(:exam_9) %></h1>
  <p><%= t_exam_content(:exam_9) %></p>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t_(:name) %></th>
      </tr>
    </thead>
    <tbody>
      <!-- Just for guide you can make your own -->
      <% @self_bought_games.each do |g| %>
        <tr>
          <td><%= g.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/dashboard/get_prime.js.erb
$('#result-get-prime').html("<%= @result %>")

app/views/dashboard/get_user_game.js.erb
$('#result-get-prime .user').html("<%= @result.email %>");
$('#result-get-prime .count').html();

app/views/dashboard/get_user_game_hard.js.erb
// Can't update this file
$('#result-get-prime .user').html("<%= @result.email %>");
$('#result-get-prime .count').html("<%= @result.games_count %>");

app/views/dashboard/index.html.erb
<% if I18n.locale == :en %>
  <h1>Guide</h1>
  <ul>
    <li>About the question, maybe you can make more clear in controller</li>
    <li>Creator relation use just for 9 - 10</li>
    <li>Pick the easy exam first we care how many what you finish in 1 hour</li>
    <li>Try to make everything query not in view</li>
    <li>Avoid to use loop inside loop if you can</li>
    <li>2 -> 3, 4 -> 5 have a similar exam if you make it well you can skip the next one</li>
    <li>You can ask the question during the exam</li>
  </ul>
<% elsif I18n.locale == :th %>
  <h1>แนวทาง</h1>
  <ul>
    <li>รายละเอียดของคำถามอาจจะเข้าใจมากขึ้นเมื่อเห็น controller</li>
    <li>Creator relation ใช้เฉพาะข้อ 9 - 10</li>
    <li>เลือกทำข้อที่ง่ายการ เน้นจำนวนที่ทำภายใน 1 ชั่วโมง</li>
    <li>พยายาทำอย่าดึงข้อมูลภายใน view</li>
    <li>พยายามหลีกเลี่ยงการเรียกลูปซ้อนลูปถ้าเป็นไปได้</li>
    <li>2 -> 3, 4 -> 5 คำถามจะคล้ายกันถ้าทำข้อแรกได้ดีสามารถข้ามอีกข้อได้</li>
    <li>ระหว่างทำข้อสอบ สงสัยตรงไหนถามได้</li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : t_title(:exam) %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to t_title(:exam), root_path, class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <% (1..10).each do |i| %>
              <li><%= link_to t_exam(i), eval("dashboard_exam_#{i}_path") %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3><%= t_(:sidebar) %></h3>
            <ul class="nav nav-list">
              <li class="nav-header"><%= t_(:language) %></li>
              <li><%= link_to t_locale(:english), params.merge(locale: "en") %></li>
              <li><%= link_to t_locale(:thai), params.merge(locale: "th") %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p><%= t_(:copy_right) %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>